"""add title field to conversion

Revision ID: 582de89bc1c5
Revises: 0070e7ef7a81
Create Date: 2025-05-25 13:47:53.989156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582de89bc1c5'
down_revision = '0070e7ef7a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
